[mypy]
python_version = 3.14
check_untyped_defs = true
warn_unused_ignores = true
ignore_missing_imports = false

[mypy-argostranslate.*]
ignore_missing_imports = true

[mypy-pytesseract]
ignore_missing_imports = true

[mypy-psutil]
ignore_missing_imports = true

[mypy-httpx2.*]
ignore_missing_imports = true
